2016-10-17 11:03:56,线程正在运行或被终止；它无法重新启动。
2016-10-17 11:03:57,连接回调失败由于目标计算机积极拒绝，无法连接。 10.201.0.46:4525
2016-10-17 11:04:09,未将对象引用设置到对象的实例。
2016-10-17 11:04:10,线程正在运行或被终止；它无法重新启动。
2016-10-17 11:05:34,线程正在运行或被终止；它无法重新启动。
2016-10-17 14:06:00,索引超出范围。必须为非负值并小于集合大小。
参数名: index
2016-10-17 14:45:01,A288接受数据失败无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。
2016-10-17 14:45:38,A288接受数据失败无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。
2016-10-17 14:46:21,A288客户端断开连接
2016-10-17 14:46:54,A288接受数据失败无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。
2016-10-17 14:48:39,A288客户端断开连接
2016-10-17 14:51:18,A288客户端断开连接
2016-10-17 15:02:26,A288接受数据失败无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。
2016-10-17 15:04:54,A288接受数据失败无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。
2016-10-17 15:08:26,索引超出范围。必须为非负值并小于集合大小。
参数名: index
2016-10-17 15:14:45,A288接受数据失败无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。
2016-10-17 15:16:55,A288接受数据失败无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。
2016-10-17 16:02:50,A288接受数据失败无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。
2016-10-17 16:03:06,A288接受数据失败无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。
2016-10-17 16:05:03,A288接受数据失败远程主机强迫关闭了一个现有的连接。
2016-10-17 16:07:17,A288客户端断开连接
2016-10-17 16:08:27,A288客户端断开连接
2016-10-17 16:13:13,A288客户端断开连接
2016-10-17 16:15:17,A288客户端断开连接
2016-10-17 16:34:45,A288客户端断开连接
2016-10-17 16:42:45,InvalidArgument=“0”的值对于“index”无效。
参数名: index
2016-10-17 16:42:49,未将对象引用设置到对象的实例。
2016-10-17 16:44:32,A288接受数据失败远程主机强迫关闭了一个现有的连接。
2016-10-17 16:47:36,A288接受数据失败无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。
2016-10-17 17:01:41,InvalidArgument=“0”的值对于“index”无效。
参数名: index
2016-10-17 17:01:45,未将对象引用设置到对象的实例。
2016-10-17 17:02:08,A288接受数据失败远程主机强迫关闭了一个现有的连接。
2016-10-17 17:27:38,A288接受数据失败无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。
2016-10-17 17:31:13,A288接受数据失败远程主机强迫关闭了一个现有的连接。
